1. Import the NUMPY package under the name np.

In [1]:
import numpy as np

2. Print the NUMPY version and the configuration.

In [6]:
np.__version__

'1.21.5'

In [7]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/danser/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/danser/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/danser/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/danser/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/danser/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/danser/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/danser/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/danser/opt/anaconda3/include']
Supported SIMD extensions in this NumPy install:
    baseline = 

3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"

Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [23]:
#4. Print a.
a = np.random.random( (2,3,5,))
a

array([[[0.20166688, 0.39344632, 0.97278534, 0.26488968, 0.11488001],
        [0.13158412, 0.39483903, 0.30747162, 0.87382106, 0.71094372],
        [0.06636076, 0.96424358, 0.37933404, 0.64388239, 0.13077674]],

       [[0.84534914, 0.47385495, 0.01706365, 0.63645746, 0.37845659],
        [0.88320469, 0.54169009, 0.84141384, 0.22818489, 0.5377629 ],
        [0.23908928, 0.62323899, 0.64531011, 0.462958  , 0.97004555]]])

In [24]:
a1 = np.random.randint(0, 100, size=(2, 3, 5))
a1

array([[[47, 28, 46, 89,  5],
        [66, 88, 37, 35, 32],
        [17,  6, 66, 38, 24]],

       [[93, 22,  7, 85, 18],
        [62, 27,  3, 80, 53],
        [56, 85, 96, 67, 35]]])

In [26]:
from numpy.random import default_rng
>>> default_rng(100).random((2,3,5))

array([[[0.83498163, 0.59655403, 0.28886324, 0.04295157, 0.9736544 ],
        [0.5964717 , 0.79026316, 0.91033938, 0.68815445, 0.18999147],
        [0.98147898, 0.28474005, 0.62927317, 0.58103648, 0.59991227]],

       [[0.53524811, 0.9957771 , 0.50194608, 0.77102258, 0.49416178],
        [0.99767449, 0.97862192, 0.39356804, 0.32192526, 0.86218065],
        [0.7993249 , 0.69143063, 0.40851785, 0.38976513, 0.1316484 ]]])

5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
6. Print b.

In [50]:
b = np.ones((5,3,2))
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

7. Do a and b have the same size? How do you prove that in Python code?

In [38]:
b.shape


(5, 2, 3)

In [39]:
a.shape

(2, 3, 5)

8. Are you able to add a and b? Why or why not?

In [40]:
#No, they would have to be the same shape:
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [51]:
c= b.T
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [153]:
#It works because they are the same shape now
d = np.add(a,c)
d

array([[[1.20166688, 1.39344632, 1.97278534, 1.26488968, 1.11488001],
        [1.13158412, 1.39483903, 1.30747162, 1.87382106, 1.71094372],
        [1.06636076, 1.96424358, 1.37933404, 1.64388239, 1.13077674]],

       [[1.84534914, 1.47385495, 1.01706365, 1.63645746, 1.37845659],
        [1.88320469, 1.54169009, 1.84141384, 1.22818489, 1.5377629 ],
        [1.23908928, 1.62323899, 1.64531011, 1.462958  , 1.97004555]]])

11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [57]:
print (a)

[[[0.20166688 0.39344632 0.97278534 0.26488968 0.11488001]
  [0.13158412 0.39483903 0.30747162 0.87382106 0.71094372]
  [0.06636076 0.96424358 0.37933404 0.64388239 0.13077674]]

 [[0.84534914 0.47385495 0.01706365 0.63645746 0.37845659]
  [0.88320469 0.54169009 0.84141384 0.22818489 0.5377629 ]
  [0.23908928 0.62323899 0.64531011 0.462958   0.97004555]]]


In [154]:
print (d)

[[[1.20166688 1.39344632 1.97278534 1.26488968 1.11488001]
  [1.13158412 1.39483903 1.30747162 1.87382106 1.71094372]
  [1.06636076 1.96424358 1.37933404 1.64388239 1.13077674]]

 [[1.84534914 1.47385495 1.01706365 1.63645746 1.37845659]
  [1.88320469 1.54169009 1.84141384 1.22818489 1.5377629 ]
  [1.23908928 1.62323899 1.64531011 1.462958   1.97004555]]]


In [64]:
d.shape

(2, 3, 5)

In [59]:
#D has all full numbers since we added 1s to it

12. Multiply a and c. Assign the result to e.

In [60]:
e = np.multiply(a,c)
e

array([[[0.20166688, 0.39344632, 0.97278534, 0.26488968, 0.11488001],
        [0.13158412, 0.39483903, 0.30747162, 0.87382106, 0.71094372],
        [0.06636076, 0.96424358, 0.37933404, 0.64388239, 0.13077674]],

       [[0.84534914, 0.47385495, 0.01706365, 0.63645746, 0.37845659],
        [0.88320469, 0.54169009, 0.84141384, 0.22818489, 0.5377629 ],
        [0.23908928, 0.62323899, 0.64531011, 0.462958  , 0.97004555]]])

13. Does e equal to a? Why or why not?

In [61]:
#E has the same values because each element was multiplied by 1 - so they remained the same

14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [63]:
d_max= np.max(d)
d_min= np.min(d)
d_mean= np.mean(d)

15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [103]:
f= np.empty(([2,3,5]))
f

array([[[ 25.,  25., 100.,  25.,  25.],
        [ 25.,  25.,  25.,  75.,  75.],
        [ 25.,  75.,  25.,  75.,  25.]],

       [[ 75.,  25.,   0.,  75.,  25.],
        [ 75.,  75.,  75.,  25.,  75.],
        [ 25.,  75.,  75.,  25.,  75.]]])

"""
16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

In [121]:
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
               if d_mean > d[i][j][k] > d_min:
                   f[i][j][k]  = 25
               if d_max > d[i][j][k] > d_mean:
                    f[i][j][k] = 75
               if  d[i][j][k] == d_mean:
                     f[i][j][k] = 50
               if  d[i][j][k] == d_min:
                    f[i][j][k] = 0
               if  d[i][j][k] == d_max:
                     f[i][j][k] = 100
            #print(d[i][j][k])
        

In [122]:
f[1][1]

array([75., 75., 75., 75., 75.])

In [112]:
f1= [[[25 if d_min<item<d_mean else 75 if d_mean<item< d_max else 0 if item == d_min else 100 for item in in_list] for in_list in out_list] for out_list in d]

In [111]:
f1

[[[25, 25, 100, 25, 25], [25, 25, 25, 75, 75], [25, 75, 25, 75, 25]],
 [[75, 25, 0, 75, 25], [75, 75, 75, 25, 75], [25, 75, 75, 25, 75]]]

In [119]:
#17. Print d and f. Do you have your expected f?
#For instance, if your d is:


In [118]:
d=   ([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

In [123]:
f

array([[[75., 75., 75., 25., 75.],
        [75., 75., 25., 75., 25.],
        [75., 25., 75., 75., 75.]],

       [[25., 25., 25., 75., 75.],
        [75., 75., 75., 75., 75.],
        [25., 75., 75., 75., 75.]]])

In [124]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
#("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
#array([[[ 'D',  'D',  'D',  'B',  'D'],
#        [ 'D',  'D',  'B',  'B',  'B'],
#        [ 'D',  'B',  'D',  'D',  'D']],
#       [[ 'B',  'B',  'B',  'B',  'E'],
#        [ 'D',  'D',  'D',  'D',  'D'],
#        [ 'B',  'D',   'A',  'D', 'D']]])

In [150]:
z = np.empty((2, 3, 5), dtype = 'str')
z

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [155]:
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
               if d_mean > d[i][j][k] > d_min:
                   z[i][j][k]  = 'A'
               if d_max > d[i][j][k] > d_mean:
                    z[i][j][k] = 'B'
               if  d[i][j][k] == d_mean:
                     z[i][j][k] = 'C'
               if  d[i][j][k] == d_min:
                    z[i][j][k] = 'D'
               if  d[i][j][k] == d_max:
                     z[i][j][k] = 'E'

In [157]:
z

array([[['A', 'A', 'E', 'A', 'A'],
        ['A', 'A', 'A', 'B', 'B'],
        ['A', 'B', 'A', 'B', 'A']],

       [['B', 'A', 'D', 'B', 'A'],
        ['B', 'B', 'B', 'A', 'B'],
        ['A', 'B', 'B', 'A', 'B']]], dtype='<U1')